### ISSUE TITLE
K8s secrets are not refreshed from vault

### ISSUE THREAD

**Issue by mthoretton** [hashicorp/vault-csi-provider#104]
Hello!

I was following this tuto https://www.vaultproject.io/docs/platform/k8s/csi/examples as I wanted to create k8s secrets from vault secrets. Then used I used `secretObjects` property and it works fine.
The issue is: when the secrets values change in vault, the new values are not refreshed in the k8s secret. I tried to restart the pod or re-apply SecretProviderClass, it doesn't work.
On the other hand, this works properly with the voulumeMounts. /mnt/secrets-store/my-secret will have the up to date value when to pod restarts.

I know this is still the beta version so maybe it's known, but as I didn't find a roadmap or so I thought it's worth creating an issue.

Thanks for the project, it's really nice!

**Comment by mstrYoda** [comment]
May be related with this: https://secrets-store-csi-driver.sigs.k8s.io/topics/secret-auto-rotation.html

Is this supported in the current CSI impl? If not I am volunteer to implement it.

**Comment by mthoretton** [comment]
🙈  That was it. Not sure how I missed this property... thanks a lot @mstrYoda  .
