### ISSUE TITLE
ARM64 build

### ISSUE THREAD

**Issue by zewelor** [hashicorp/vault-csi-provider#105]
It is possible to provide arm64 build ?

**Comment by amoravek** [comment]
Vote for this too - setting --set="csi.enabled=true" on the official Vault Helm chart while installing on ARM64 system ends with working Vault and failing Vault CSI provider (exec format error). Thank you in advance.

**Comment by tomhjp** [comment]
0.4.0 was published today, with `amd64`, `arm64`, `386` and `arm/v6` all included. Let us know if you have any issues with it!

**Comment by tomhjp** [comment]
Forgot the link, just for ease: https://hub.docker.com/r/hashicorp/vault-csi-provider/tags

**Comment by mtecer** [comment]
@tomhjp Thank you.
