### ISSUE TITLE
Support for secret encoding?

### ISSUE THREAD

**Issue by schantaraud** [hashicorp/vault-csi-provider#106]
It seems that a common way of storing non-Unicode secrets in Vault is to base64-encode them. Is there currently a way to mount these through the CSI provider without adding a manual decoding process?
If not, the Azure driver supports an `objectEncoding` property (see https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/236). Would you accept a PR that adds a similar feature?

**Comment by bimtauer** [comment]
Same here, this would be great to have. We run some third party services that require certificates in pem string format but we have them base64 encoded everywhere else in Vault.

**Comment by LianwMS** [comment]
@therealsamlin and @bimtauer, then how did you resolve such issue? We have the same issue here.

**Comment by tomhjp** [comment]
Fixed by #194. Thanks for the contribution @BroCanDo!
