### ISSUE TITLE
Auto rotation support

### ISSUE THREAD

**Issue by aw1cks** [hashicorp/vault-csi-provider#107]
Hey,
was wondering if secret auto rotation is supported? As per https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/125 the CSI supports it, I can see plenty of references to Azure on this issue but have been drawing a blank from documentation as to whether the Vault provider supports this.

**Comment by tomhjp** [comment]
As far as I'm aware, the provider doesn't need to do anything special to support secret rotation, it's just a feature of the driver. I've just given it a little test run locally and it seems to work fine. Please do open up an issue if you find anything about it that doesn't work as expected though. https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/724 should also help clarify this once it lands too.
