### ISSUE TITLE
How to get all secrets in a file

### ISSUE THREAD

**Issue by adrafiq** [hashicorp/vault-csi-provider#114]
Played with the demo. But practically having hundreds of services and scores of secret values. The objectName practice become tedius. Is there any way to pull all of the values under one secret inside a kubernetes secret. ?

**Comment by tomhjp** [comment]
Not currently, but there is an open issue and pull request on the CSI driver repo that I think addresses your ask: https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/529. It's had a lot of support from the maintainers during design, so I would expect it should land sooner or later.
