### ISSUE TITLE
fetching complex JSON from Vault

### ISSUE THREAD

**Issue by rkennedy-tpl** [hashicorp/vault-csi-provider#115]
from the changelog...

```
If secretKey is set, that is the key from the secret's data that will be written
If secretKey is not set, the whole JSON response from Vault will be written
```

I have complex JSON data stored in Vault, example (heavily redacted, use your imagination):

![image](https://user-images.githubusercontent.com/76958947/137504481-e3a7c0a7-261d-4c51-9b91-3b6f0bb1fabf.png)

the data shows up correctly when `secretKey` is excluded. however, the "whole JSON response" shows up and it includes extra details, ex:

```
$ head /mnt/secrets-store/fabricProfile 
{"request_id":"deadbeef-xxxx-yyyy-zzzz-moreredactedhex","lease_id":"","lease_duration":0,"renewable":false,"data":{"data":{"certificateAuthorities":{"hlf-ca--unicorn":{....
```

I tried setting `secretKey` to a variety of things like `data` `Data` `.data` to see if I could trick the provider into sending me the JSON body without the extraneous response "envelope".

is there a specific key I can use when fetching JSON blocks? I was really hoping to leverage JSON instead of only key/value pairs. or is this something that would require code-changes to the `vault-csi-provider` to support?

**Comment by agates4** [comment]
Got it working

In the secret provider, no `secretKey` should be specified
```
      - objectName: "vault-gcr-json-key-object"
        secretPath: "secret/data/buildkite/gcr_json_key"
```

as a mounted secret, `.Data.data` should be specified as the key
```
    - secretName: vault-gcr-json-key
      type: Opaque
      data: 
        - objectName: vault-gcr-json-key-object
          key: .Data.data
```

cheers 🥂

**Comment by rkennedy-tpl** [comment]
I mean, `vault-csi` is still writing a file today, it's just "enveloped" with some extraneous metadata. I might tell my developers to "expect to de-envelope configs" or I can throw some random shim-code in somewhere that de-envelopes the configs before starting the application workloads. this is by no means a "game-breaking bug", it's just "mildly inconvenient" for some SDE Teams, who I have little control over ;)

I actually wound up investigating `vault-csi` over `vault-injector` because it seemed like [this comment](https://github.com/hashicorp/vault-k8s/issues/14#issuecomment-815925644) was saying "we added ENV to `vault-csi` and thus aren't bothering to add it to `vault-injector`." using CSIs also seems to be the more "modern" Kubernetes way of doing things, so I suspect `vault-csi` will be getting more and more attention as time passes, possibly quietly leaving `vault-injector` behind in terms of feature-set and community support.

**Comment by agates4** [comment]
it's worth noting that the CSI is also much faster than the vault injector, where the vault injector may take a few seconds and blocks the creation of parallel replica sets due to requiring the container to finish before starting the next replica set ..

so, because the CSI is more modern and faster, I would like to feature request this **"de-envelope"** concept.

**Comment by rkennedy-tpl** [comment]
I think things become even more complex when you consider the `pki` provider, ala https://github.com/hashicorp/vault-csi-provider/blob/d6ab1a58a4c40a5bf6df8e5d015d97263be5801c/test/bats/configs/vault-all-secretproviderclass.yaml#L22-L27

without a `secretKey` defined, I'm getting back the entire PKI JSON as expected.

I can select out the certificate into an individual file using `secretKey`, but then how do I select `privateKey` or `issuingCa` if I want to drop those into the same Pod at the same time? if I run multiple `issue/` paths as objects, won't I be issuing 2 certificates and thus mis-matching my Cert and PrivateKey ?

**Comment by agates4** [comment]
On line 205, the secret is created as a json and then returned as bytes 
https://github.com/hashicorp/vault-csi-provider/blob/master/internal/provider/provider.go#L203-L211

Perhaps here, if there is no SecretKey it could check for some config variable like SecretJsonPath or something: check if the path exists, then return the value of that path as a json

**Comment by agates4** [comment]
why does the content here need to be a string?
https://github.com/hashicorp/vault-csi-provider/blob/master/internal/provider/provider.go#L167-L170

if it was retrieved as a json instead, it would have the same result if it was just a string, and have the added bonus of being able to return a full json.
```
	bytes, ok := json.Marshal(data[secretKey])
	if ! ok {
		return "", err
	}
	 return string(bytes), nil
```

this would support loaded JSONs as environment variable secrets

**Comment by tomhjp** [comment]
Thanks for the input all. Hopefully #126 addresses this feature request. It won't support extracting keys any deeper than the top level (I don't think this is really part of the request, but just being explicit), but it can now handle JSON values in that top level.

> if I run multiple issue/ paths as objects, won't I be issuing 2 certificates and thus mis-matching my Cert and PrivateKey ?

As you discovered, it will only query each [path, method] pair once per _SecretProviderClass_, so you can indeed extract multiple keys from a single response. It's not the most intuitive, but this stems from an `object` or file being the atomic unit of interest for the driver. Perhaps this could be improved in the future.

**Comment by agates4** [comment]
[0.4.0](https://github.com/hashicorp/vault-csi-provider/actions/runs/1689231343) worked as expected! Thanks again @tomhjp!
```
src# echo $testing_json
{"json_key_1":true,"json_key_2":4,"json_key_3":"did it","json_key_4":{"complex_json":"yes"}}
```

**Comment by rkennedy-tpl** [comment]
thanks! I'm buried with some other more pressing matters, but I'll try to test my use-case in the next 2-3 weeks 👍

**Comment by tomhjp** [comment]
Awesome, thanks for testing this! It's also now published on Docker hub, including a few extra CPU arch images for the first time 🙂 https://hub.docker.com/r/hashicorp/vault-csi-provider/tags
