### ISSUE TITLE
problems with CLusterRole resources

### ISSUE THREAD

**Issue by artarik** [hashicorp/vault-csi-provider#135]
Hello.
i have a k8s cluster with 3 worker nodes, v.1.22.3 where installed Vault-ha-raft cluster named `vault-raft` with vault-csi-provider in namespace `vault`
Everything installed via helm as described in tutorials.
I created a serviceaccount `sas-kv` and simple pod  in test namespace called `csi` for checking workability
But then i try to start pod,  it`s falls with error:
``` Events:
  Type     Reason       Age               From               Message
  ----     ------       ----              ----               -------
  Normal   Scheduled    25s               default-scheduler  Successfully assigned csi/nginx-csi-test to k8s-worker1
  Warning  FailedMount  9s (x6 over 25s)  kubelet            MountVolume.SetUp failed for volume "secrets-volume" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod csi/nginx-csi-test, err: rpc error: code = Unknown desc = error making mount request: failed to create a service account token for requesting pod {nginx-csi-test 59b0e7c4-79c3-4b6b-98e6-3f7927f208f2 csi sas-kv}: serviceaccounts "sas-kv" is forbidden: User "system:serviceaccount:vault:vault-csi-provider" cannot create resource "serviceaccounts/token" in API group "" in the namespace "csi" 
 ```

  
As far as i understood a problem with created ClusterRole `{{ vault.name }}-csi-provider-clusterrole` in area `resources`

If i check permissions for ServiceAccount `system:serviceaccount:vault:vault-csi-provider` via `kubectl auth`,it return `no`:
```
$ kubectl auth can-i create serviceaccount/token -n csi --as=system:serviceaccount:vault:vault-csi-provider
no
```
But if i change a ClusterRole like this:
```
...
  resources:
  - serviceaccounts/token
  - serviceaccounts #<--- added this resource
  verbs:
  - create
```
ServiceAccount `{{ vault.name }}-csi-provider` get permissions, pod run successfully and i can see my secrets from Vault.
So what i missing while configure vault with csi?
I don`t want to get access to ServiceAccount create other ServiceAccounts.
Does i need a create a same Role and RoleBinding in my new namespaces, where i want to get secret from vault via csi?

**Comment by tomhjp** [comment]
Hmm that ClusterRole change shouldn't have any effect. One note, is that I believe the `can-i` command should use `--subresource` for the token portion:

```bash
kubectl auth can-i create serviceaccounts --subresource=token -n csi --as=system:serviceaccount:vault:vault-csi-provider
```

I have tried to reproduce but I'm not getting the same issue. From a fresh `kind` cluster:

```bash
kubectl create namespace csi
kubectl create namespace vault
helm install secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/secrets-store-csi-driver-1.0.1.tgz?raw=true \
     --wait --timeout=5m \
     --namespace=csi \
     --set linux.image.pullPolicy="IfNotPresent" \
     --set syncSecret.enabled=true
helm install vault https://github.com/hashicorp/vault-helm/archive/v0.19.0.tar.gz \
    --wait --timeout=5m \
    --namespace=csi \
    --set server.dev.enabled=true \
    --set csi.enabled=true
kubectl create serviceaccount -n csi sas-kv
kubectl apply -n csi -f-<<EOF
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv
spec:
  provider: vault
  parameters:
    roleName: "kv-role"
    vaultAddress: http://vault:8200
    objects: |
      - objectName: "secret-1"
        secretPath: "secret/data/kv1"
        secretKey: "bar1"
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  serviceAccountName: sas-kv
  terminationGracePeriodSeconds: 0
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "kv"
EOF
k describe pod nginx -n csi
...failed to login... # <--- This means it managed to create the k8s token fine and then failed at Vault login because I didn't set up the k8s auth mount
```

**Comment by artarik** [comment]
hmm. i changed node and everything work as it should. go to troubleshoot node. Thank`s for you feedback

**Comment by artarik** [comment]
problem with node

**Comment by wibram** [comment]
I have the same issue described here:
https://discuss.hashicorp.com/t/user-vault-csi-provider-cannot-create-resource-serviceaccounts-token/59859
and here:
https://stackoverflow.com/q/77444189/448100

What was the reason and solution? I don't understand what is meant with "changed node". Can you share your solution please @artarik ?
