### ISSUE TITLE
multi-arch support for container images

### ISSUE THREAD

**Issue by developer-guy** [hashicorp/vault-csi-provider#137]
We can build container images capable of running in different CPU architectures. Feel free to assign to me if you accept this issue, I'm willing to work on this 🤩

**Comment by tomhjp** [comment]
Hi @developer-guy, the latest versions published on Docker hub are already multi-arch: https://hub.docker.com/layers/hashicorp/vault-csi-provider/latest/images/sha256-9f7a38acf7a4426993a3c1d738c0426989f464eb532dea51a5313d5e95f4932a?context=explore. We have `386`, `arm64`, `arm/v6` and `amd64`. Feel free to comment again if you have a more specific ask not already covered by those.
