### ISSUE TITLE
`SecretProviderClassPodStatus` doesn't update status because `version` is hard-coded to 0

### ISSUE THREAD

**Issue by mdrakiburrahman** [hashicorp/vault-csi-provider#146]
_Moved issue from CSI Driver as it is Vault provider specific: [here](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/868)_

I'd like to see `secretproviderclasspodstatus` tell me when the secret version was changed in the pod as documented [here](https://secrets-store-csi-driver.sigs.k8s.io/topics/secret-auto-rotation.html#how-to-view-the-current-secret-versions-loaded-in-pod-mount). 

This works fine for other CSI providers such as AKV, but for Vault the secret version does not change even though the pod mounted file is changing. This is useful for other Operators that depend on Vault secret versions to reconcile updates (such as login rotations).

**Vault provider issue**
Upon digging further I see the issue is [here](https://github.com/hashicorp/vault-csi-provider/blob/main/internal/provider/provider.go#L255), we are hardcoding `version` to "0" regardless what the Provider returns:
```go
versions[fmt.Sprintf("%s:%s:%s", secret.ObjectName, secret.SecretPath, secret.Method)] = "0" // <--- problem
```

**Why AKV works**
On the other hand, [here](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/9492015b2544d4fb7ceb13aa524870c2035d0c88/pkg/server/server.go#L72) we can see that for a similar mount operation AKV appends the actual version received from the EKM into the return object:
```go
for _, file := range files {
		f = append(f, &v1alpha1.File{
			Path:     file.Path,
			Contents: file.Content,
			Mode:     file.FileMode,
		})

		ov = append(ov, &v1alpha1.ObjectVersion{
			Id:      file.UID,
			Version: file.Version, // <--- solution
		})
	}
```

cc: @aramase 

I'm happy to PR the fix as it looks fairly trivial but I'm not sure what the process to contribute/test changes to the Vault CSI provider is.

---
### Repro steps

To repro, here's the full script I deployed playing around with Vault CSI, with the relevant pieces pulled out below:
https://github.com/mdrakiburrahman/vault-csi-demo/blob/main/deployment.sh

```shell
################################################
# Install Helm Chart
################################################
# Install CSI helm chart with auto rotation
helm install csi csi-secrets-store-provider/csi-secrets-store-provider \
            --set secrets-store-csi-driver.enableSecretRotation=true \
            --set secrets-store-csi-driver.rotationPollInterval=5s

################################################
# Create a SecretProviderClass
################################################
cat > spc-vault-database.yaml <<EOF
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
...
spec:
  parameters:
    vaultAddress: "http://vault.default:8200"
    objects: |
      - objectName: "db-password"
...
EOF

kubectl apply -f spc-vault-database.yaml

cat > pod.yaml <<EOF
kind: Pod
apiVersion: v1
...
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
...
EOF
kubectl apply -f pod.yaml

# Read secret from pod
kubectl exec busybox-secrets-store-inline -- cat /mnt/secrets-store/db-password
# db-secret-password

################################################
# Secret version
################################################
# Get Secret Version
kubectl get secretproviderclasspodstatus busybox-secrets-store-inline-default-vault-database -o yaml
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClassPodStatus
# metadata:
#   creationTimestamp: "2022-02-10T02:53:40Z"
#   generation: 1
#   labels:
#     internal.secrets-store.csi.k8s.io/node-name: aks-agentpool-21566404-vmss00003o
#   name: busybox-secrets-store-inline-default-vault-database
#   namespace: default
#   ownerReferences:
#   - apiVersion: v1
#     kind: Pod
#     name: busybox-secrets-store-inline
#     uid: c31afb1c-238d-47ed-bc57-02031e13315b
#   resourceVersion: "16170051"
#   selfLink: /apis/secrets-store.csi.x-k8s.io/v1/namespaces/default/secretproviderclasspodstatuses/busybox-secrets-store-inline-default-vault-database
#   uid: 825ce2f1-3391-41fd-886c-c7abc4b13208
# status:
#   mounted: true
#   objects:
#   - id: 'db-password:secret/data/db-pass:'
#     version: "0"
#   podName: busybox-secrets-store-inline
#   secretProviderClassName: vault-database
#   targetPath: /var/lib/kubelet/pods/c31afb1c-238d-47ed-bc57-02031e13315b/volumes/kubernetes.io~csi/secrets-store-inline/mount

# Update secret in Vault UI
# my-new-updated-password

# Read secret from pod
kubectl exec busybox-secrets-store-inline -- cat /mnt/secrets-store/db-password
# my-new-updated-password <---------------- ⭐⭐⭐⭐⭐⭐⭐ Updated fine in 5 seconds

# Get Secret Version
kubectl get secretproviderclasspodstatus busybox-secrets-store-inline-default-vault-database -o yaml
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClassPodStatus
# metadata:
#   creationTimestamp: "2022-02-10T02:53:40Z"
#   generation: 1
#   labels:
#     internal.secrets-store.csi.k8s.io/node-name: aks-agentpool-21566404-vmss00003o
#   name: busybox-secrets-store-inline-default-vault-database
#   namespace: default
#   ownerReferences:
#   - apiVersion: v1
#     kind: Pod
#     name: busybox-secrets-store-inline
#     uid: c31afb1c-238d-47ed-bc57-02031e13315b
#   resourceVersion: "16170051"
#   selfLink: /apis/secrets-store.csi.x-k8s.io/v1/namespaces/default/secretproviderclasspodstatuses/busybox-secrets-store-inline-default-vault-database
#   uid: 825ce2f1-3391-41fd-886c-c7abc4b13208
# status:
#   mounted: true
#   objects:
#   - id: 'db-password:secret/data/db-pass:'
#     version: "0" <---------------- ⭐⭐⭐⭐⭐⭐⭐ Nothing has changed even though pod mount changed since Provider is returning "0"
#   podName: busybox-secrets-store-inline
#   secretProviderClassName: vault-database
#   targetPath: /var/lib/kubelet/pods/c31afb1c-238d-47ed-bc57-02031e13315b/volumes/kubernetes.io~csi/secrets-store-inline/mount
```

**Comment by tomhjp** [comment]
Hi @mdrakiburrahman, thanks for the detailed report and repro steps. As far as contributing goes, an issue is an excellent first step so we can discuss the solution we'd like to see!

The reason it's currently hardcoded to 0 is because when I wrote that code I felt there was no obviously correct and consistent version to use. As you point out, the Azure provider does set the version but AFAIU that version comes directly from the API response. Some of Vault's secret engines have a version, such as KV v2, but most don't. So the options I considered (including mixing and matching between them) at the time were:

* Use a version when provided in the API response
  * I think KV v2 may literally be the only one
  * We then don't have a consistent usage of the field
* Auto-increment the version every time the mount point is called
  * That means the version will increment even when the contents don't change (e.g. KV secrets), and may cause unnecessary churn
* Cache the secret contents and only increment the version when it changes
  * I don't love that we'll be holding onto secret material for longer than we need to

Now that I have your use case in front of me, I think we can do better than the above:

* Set the version to a consistent hash of the contents
  * Solves the objections above, but then the versions don't have ordering
* Or maybe, cache the hash of the secret contents, and increment an integer version whenever that changes
  * Gives ordered versions, but I don't think there's any way the provider can know when it's safe to evict items from the cache, so it's kind of a built-in memory leak, albeit a very slow one in most non-pathological cases.

That brings me to my key question:

> This is useful for other Operators that depend on Vault secret versions to reconcile updates (such as login rotations).

You mention in passing your use-case - please could you expand on this in a little more detail? I think understanding how the version will be consumed is key to making a good decision here. It sounds like the lack of version ordering would probably not be an issue, and I feel like it probably wouldn't be in most cases, so currently I am leaning towards the hash version idea.

**Comment by mdrakiburrahman** [comment]
Hey @tomhjp - I appreciate the thoughtful response. 

You're right, when we consider the different permutations of back-end secret stores Vault supports - kv1, kv2, cubbyhole etc - I understand the complexity skyrockets compared to Azure Key Vault/others where life is simpler. That being said - the need for versioning is real, and KV2 introduced this feature to solve this exact problem as Hashicorp has documented [here](https://learn.hashicorp.com/tutorials/vault/versioned-kv).

Sharing my perspective, the project I'm working on has enterprise use of everything - KV1, KV2 and Cubbyholes etc, but for the specific K8s Operator Use Case I will explain below, we would get unblocked if the Vault CSI could only provide KV2 versioning that came out of the API to start - i.e. this:

```bash
vault kv get secret/db-pass-vault
# ======= Metadata =======
# Key                Value
# ---                -----
# created_time       2022-02-22T01:42:01.74593273Z
# custom_metadata    <nil>
# deletion_time      n/a
# destroyed          false
# version            2             <-- Expose this in SecretProviderClassPodStatus similar to AKV from the API (AKV API provides a GUID not a nice integer like this)
```
And for KV1 backends, keep it 0 as you have it today, until the more sophisticated sync mechanism is figured out (hashing as you've described).  Perhaps a metadata field or label can be added to distinguish the KV2 secrets from KV1. I think we could reach a reasonable solution this way to at least get feature parity for those that have Vault and need to know about Versioning events in some form within K8s.
 
> * Use a version when provided in the API response
>   * I think KV v2 may literally be the only one
>   * We then don't have a consistent usage of the field

From my perspective the "consistent usage" isn't a massive dealbreaker since Vault itself has inconsistent backends so we use the one that aligns closest with the CSI spec (KV2).

> * Auto-increment the version every time the mount point is called
>   * That means the version will increment even when the contents don't change (e.g. KV secrets), and may cause unnecessary churn

If this was implemented, the way we were planning on using the K8s events via an informer would bombard our Operator with events. Also, if `secrets-store-csi-driver.rotationPollInterval` was set to some small number (seconds) `SecretProviderClassPodStatus` CRD would change extremely often.

> * Cache the secret contents and only increment the version when it changes
>   * I don't love that we'll be holding onto secret material for longer than we need to

Our security team would have a heart attack over this if they found out 😊

> * Set the version to a consistent hash of the contents
>   * Solves the objections above, but then the versions don't have ordering

This would be aligned with with AKV does today, you get a GUID - 
![image](https://user-images.githubusercontent.com/46581776/155054311-0fa176fa-285e-42f6-89a0-3860ab548962.png)

I see in the `SecretProviderClassPodStatus` CRD has [`metadata.generation`](https://github.com/mdrakiburrahman/secrets-csi-demo/blob/80ca948454cfa2189f767b3571ae13c395620614/deployment.sh#L513) which does seem to provide a human readable versioning mechanism as an integer (unless there are other actions besides the Secret Auto Rotation that can change this value - I haven't looked into this).

> * Or maybe, cache the hash of the secret contents, and increment an integer version whenever that changes
>   * Gives ordered versions, but I don't think there's any way the provider can know when it's safe to evict items from the cache, so it's kind of a built-in memory leak, albeit a very slow one in most non-pathological cases.

This might not be needed given the approach above to align with AKV?

> That brings me to my key question:
> You mention in passing your use-case - please could you expand on this in a little more detail? I think understanding how the version will be consumed is key to making a good decision here. It sounds like the lack of version ordering would probably not be an issue, and I feel like it probably wouldn't be in most cases, so currently I am leaning towards the hash version idea.

Sure - let me elaborate.

So we are building a Database Operator for SQL and Postgres. Today, we have end users provide the Database Superuser Creds (Login, Password) as a K8s secret as you can [see here](https://github.com/microsoft/azure_arc/blob/14a669810d1e3be6f7cce8e390249941cf46e4f6/arc_data_services/deploy/yaml/sqlmi.yaml#L3). The Database CRD has a reference to the K8s secret in it's CRD ([here](https://github.com/microsoft/azure_arc/blob/14a669810d1e3be6f7cce8e390249941cf46e4f6/arc_data_services/deploy/yaml/sqlmi.yaml#L25)) - and it uses the CRD + K8s secret to spin up the Database Pods, configure the User login etc etc.

When it comes time to rotate the User Login, the end-user can change the K8s secret, which the Database Operator listens to for updates, and goes into the Database to perform the necessary changes. User can continue logging in with the K8s secret as the source of truth.

This is one such secret, the Operator leverages many User-provided secrets, such as Certs etc.

The problem as you can imagine because auditability, access control, lifecycle management/rotations etc which is a pain on K8s secrets. We'd also like to externalize sensitive secrets out of K8s as much as reasonably possible so that K8s admins do not have an easy way into the user database. All of this is where the enterprise investment in Hashicorp Vault pays off.

So now, what we're trying to do is, rip out these User-Provided secrets, and keep them in Vault - which is where we are looking to use the CSI - since it's consistent across the main providers (Hashi/Azure/AWS/GCP) where our Operator is supported. This way, we don't have to maintain an SDK for every new Secret Store provider and can interface through the CSI route.

So, this is why it's key for the CSI provider (Vault) to let my Operator down in K8s know when the User has changed the version inside KV in a Kubernetes native manner (Informers, watchers etc) - so that I can use that event to perform all the necessary Database changes (rotate passwords, certs etc).

First time deployment:
1. User onboards Secret Store CSI, Vault Provider, `SecretProviderClass` with all the necessary [`objects`](https://github.com/mdrakiburrahman/secrets-csi-demo/blob/80ca948454cfa2189f767b3571ae13c395620614/deployment.sh#L183) array
2. We update [our CRD](https://github.com/microsoft/azure_arc/blob/main/arc_data_services/deploy/yaml/sqlmi.yaml#L11) to hook up with the CSI provider of choice (AKV, Vault etc.)
3. We create/configure the Database as we usually would with K8s secrets

And for Lifecycle management:
1. User updates whatever creds in Vault as often as their organization policies require (e.g. 90 days)
2. Our operator listens for updates to `SecretProviderClassPodStatus` to know when a Secret Version has changed. What is the actual Version number is less important than us knowing of the _event_ - since that tells us we need to take the mounted secret (which is also changed), and perform what we did in Step 3 above.

If Versioning _wasn't_ externalized by the CSI, this makes our lives really hard - because we don't know when the secret has changed. In this scenario, if we wanted to support Hashicorp Vault similar to AKV etc, then our only choice would be something like a custom File Watcher that watches the mount point, but the problem here would be edge cases (like what if our pod was down when the secret was changed by the CSI, and the pod starts up with the new secret, how would we know it changed?) - this becomes brittle.

Thanks,
Raki

**Comment by tomhjp** [comment]
Interesting point about `metadata.generation`. It looks like that and `metadata.resourceVersion` are both system-managed values that will change every time an object is updated [[ref](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#objectmeta-v1-meta)]. So they're downstream of any status changes - i.e. we still need to update the version (or anything else) ourselves to effect any change in those fields.

Thanks for the detailed feedback and use-case explanation. That really is _incredibly_ useful. I've had a go at a fix in #148. I played around with a mix of KV v2 version when it was available, and a hash otherwise, but overall it felt like a lot of work for no benefit given the version will be treated opaquely. So instead the PR just always creates hash versions. We could always add versions directly from metadata at a later date if there is a compelling reason though.

**Comment by s3than** [comment]
Any information on if the PR will be released?

**Comment by tomhjp** [comment]
Thanks for the reminder, I'll revive the PR. It should be released within the next few weeks or so.
