### ISSUE TITLE
Add the container image to the public ECR registry

### ISSUE THREAD

**Issue by bakeemawaytoys** [hashicorp/vault-csi-provider#162]
Would it be possible to push the container image to [Hashicorp's public ECR registry](https://gallery.ecr.aws/hashicorp/)?  I'd like to use the public ECR registry instead of Docker Hub so that I can avoid rate limiting.

**Comment by tomhjp** [comment]
Thanks for raising, that's a good idea. I'll see if we can get that added to the release targets.
