### ISSUE TITLE
error making mount request: failed to login: Error making API request

### ISSUE THREAD

**Issue by eravindar12** [hashicorp/vault-csi-provider#168]
error making mount request: failed to login: Error making API request, how to fix this issue?

2022-08-02T21:11:38.710Z [INFO]  server: Finished unary gRPC call: grpc.method=/v1alpha1.CSIDriverProvider/Mount grpc.time=3.701903602s grpc.code=Unknown
  err=
  | error making mount request: failed to login: Error making API request.
  |
  | URL: POST http://vault:8200/v1/auth/kubernetes/login
  | Code: 503. Errors:
  |
  | * Vault is sealed
  
  ==>
  
  2022-08-02T21:13:27.538Z [INFO]  server: Finished unary gRPC call: grpc.method=/v1alpha1.CSIDriverProvider/Mount grpc.time=3.759421801s grpc.code=Unknown
  err=
  | error making mount request: couldn't read secret "xxxxx": Error making API request.
  
  ==>

failed to rotate objects for pod xxx/xxxx, err: rpc error: code = Unknown desc = error making mount request: failed to login: Error making API request.

	URL: POST http://vault:8200/v1/auth/kubernetes/login
	Code: 503. Errors:

	* Vault is sealed

**Comment by sakiib** [comment]
Hi, what I understand: `MountRequest` needs to be `authenticated` first, by `login` to the `Vault`, then only it can read the secrets & give a `MountResponse`. This can't be done if the `Vault` is in a `Sealed` state. This is clearly shown in the error message that you've shared. Hope this helps!
FYI:
- https://www.vaultproject.io/api-docs/system/health#read-health-information
- https://www.vaultproject.io/docs/concepts/seal#seal-unseal

**Comment by tomhjp** [comment]
Thanks @sakiib, that's correct, Vault does need to be unsealed to use it. The above links are great, and also here is the unseal command documentation: https://www.vaultproject.io/docs/commands/operator/unseal.
