### ISSUE TITLE
Docker image not uploaded to ECR public

### ISSUE THREAD

**Issue by stdmje** [hashicorp/vault-csi-provider#184]
Hello,

Looks like the `vault-csi-provider` image is not being updated in ECR public registry.

https://gallery.ecr.aws/hashicorp?page=1

https://gallery.ecr.aws/hashicorp/vault-csi-provider

`vault` and `vault-k8s` are being updated so please, upload this one too.

**Comment by tomhjp** [comment]
Hi @stdmje, as of recently we're all set up for pushing future releases to ECR, we just haven't done a release since then. Looks like we've got some dep updates queued up that justify a patch release, so I'll get one going soon.

**Comment by tomhjp** [comment]
1.2.1 just went out: http://public.ecr.aws/hashicorp/vault-csi-provider:1.2.1. Do let us know if you have any issues with it. Thanks!
