### ISSUE TITLE
Running Cloud Control Manager in vcluster

### ISSUE THREAD

**Issue by Chakravarti-Baratam** [hashicorp/vault-csi-provider#185]
Hi,

When trying to run Cloud Control Manager in vcluster, the external ip field of load balancer stays stuck on 'Pending'.  When creating a load balancer in a vcluster, the event is going to both CCM, the one on the host and the one in the vcluster. but only the response from the host one is used. The response from the vcluster one is discarded.

Is there a way to use the CCM from the current vcluster instead of the host cluster?

**Comment by tomhjp** [comment]
I think this may be opened on the wrong project, but please feel free to correct me and provide more details if you're having issues using the Vault CSI Provider.
