### ISSUE TITLE
Permission denied when trying to access secret from vault on another kubernetes cluster .

### ISSUE THREAD

**Issue by pratiyush05** [hashicorp/vault-csi-provider#190]
Version :
Vault provider - 1.2.0

Description -
Trying to fetch secrets from vault which is present in different kubernetes cluster .
Cluster A - vault server
Cluster B - vault-csi-provider + SecretProviderClass.yaml + POD (which will be using secrets)
We deployed vault-csi-provider in cluster B using config mentioned here - _https://github.com/hashicorp/vault-csi-provider#using-yaml_
Using same parameters in ClusterRole and ClusterRoleBinding .

Error obtained in vault-csi-provider's logs -
```
server: Processing unary gRPC call: grpc.method=/v1alpha1.CSIDriverProvider/Mount 
server: Finished unary gRPC call: grpc.method=/v1alpha1.CSIDriverProvider/Mount grpc.time=39.006407ms grpc.code=Unknown
err=
error making mount request: failed to login: Error making API request.
URL: POST https://<vault-server-address>/v1/auth/kubernetes/login
Code: 403. Errors:
* permission denied
```
When this error occurred - 
On deploying the POD , vault-csi-provider tried to access the secret at secretPath in vault which is defined in SecretProviderClass.yaml file .

We figured out that this api - ``` https://<vault-server-address>/v1/auth/kubernetes/login``` uses JWT created/requested by vault-csi-provider .Any possible way to authorise vault-csi-provider to access inter cluster vault secrets ?

**Comment by sgargan** [comment]
It shouldn't really matter where your vault server is so long as the csi driver in the other k8s cluster can hit it. What you'll need to do is make sure that you've [configured kubernetes auth](https://developer.hashicorp.com/vault/docs/auth/kubernetes) for the k8s cluster you want to use the secrets in. 

When a pod starts up and wants a secret, it will use its service account to retrieve it from vault. It will use it's serviceaccount JWT to login to vault and get a vault token to retrieve the secrets. The vault server needs a serviceaccount in the same cluster that it  can use to validate the pod service account JWTs. 

If you follow through the linked auth setup you should be good. Make sure to pay particular attention to the RBAC config [here](https://developer.hashicorp.com/vault/docs/auth/kubernetes#configuring-kubernetes)

**Comment by tomhjp** [comment]
Just to add to that, given your setup with CSI (only supports k8s auth) and Vault outside your client k8s cluster, you're limited to options 2 and 3 from this table: https://developer.hashicorp.com/vault/docs/auth/kubernetes#how-to-work-with-short-lived-kubernetes-tokens. So the RBAC mentioned above should either be applied to every service account in cluster B that uses Vault, or to a specially created service account in cluster B whose long-lived service account you give to vault as `token_reviewer_jwt` when configuring k8s auth on it.
