### ISSUE TITLE
vault-csi-provider Pod throws cannot unmarshal !!map into []config.Secret

### ISSUE THREAD

**Issue by dkirrane** [hashicorp/vault-csi-provider#195]
I see the following in the vault-csi-provider Pod

```
2023-02-24T17:39:43.844Z [INFO]  server: Finished unary gRPC call: grpc.method=/v1alpha1.CSIDriverProvider/Mount grpc.time="357.302µs" grpc.code=Unknown
  err=
  | yaml: unmarshal errors:
  |   line 1: cannot unmarshal !!map into []config.Secret
```

I have `csi.debug=true` enabled but not getting much in the logs to help debug this issue.

My application Pod fails to start with

`MountVolume.SetUp failed for volume "secrets-volume" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/kafka-stream-sample-0, err: rpc error: code = Unknown desc = yaml: unmarshal errors: line 1: cannot unmarshal !!map into []config.Secret`

Helm Chart versions for Vault Provider & CSI Driver:

![image](https://user-images.githubusercontent.com/1280116/221250749-97f163dd-86a0-4bdc-a7fa-824b9bb347c8.png)

![image](https://user-images.githubusercontent.com/1280116/221250831-afe2cd16-18ab-4a5d-8320-12aa1e080114.png)

**Comment by tomhjp** [comment]
Please can you share your SecretProviderClass spec? It sounds like it's in slightly the wrong format. Here's an example of a valid spec: https://github.com/hashicorp/vault-csi-provider/blob/main/test/bats/configs/vault-kv-secretproviderclass.yaml

**Comment by tomhjp** [comment]
I'll close for now, but feel free to re-open if the above doesn't help you solve the issue.
