### ISSUE TITLE
Need to release new version as crypto CVE is fixed

### ISSUE THREAD

**Issue by saranyareddy24** [hashicorp/vault-csi-provider#239]
Hi,

Can you please release a new version as golang.org/x/crypto related CVE is fixed by dependabot last month.

**Comment by tvoran** [comment]
Thanks, [v1.4.2](https://github.com/hashicorp/vault-csi-provider/releases/tag/v1.4.2) has been released, which should address that CVE.

Also please email [security@hashicorp.com](mailto:security@hashicorp.com) for all vulnerability reports.
