### ISSUE TITLE
Hashicorp Vault Enterprise namespace support

### ISSUE THREAD

**Issue by wilmanpabel** [hashicorp/vault-csi-provider#65]
Namespace support need in Hashicorp Vault enterprise.
maybe as a parameter in secretProviderClass yaml like vaultNamespace:

<img width="856" alt="Screen Shot 2021-02-15 at 18 06 01" src="https://user-images.githubusercontent.com/8837805/108000654-786ce480-6fb8-11eb-844a-695ca08693df.png">

**Comment by tomhjp** [comment]
This is a great feature request, thanks for raising it! I think adding `vaultNamespace` to the SecretProviderClass yaml would be perfect.

For now I think you should still be able to use namespaces by prefixing your secret path with the namespace (do let me know if that doesn't work), but we'll add the namespace config option as well.

**Comment by PaulJDix** [comment]
This is a critical piece for us to make use of the CSI Driver for vault at our company. No additional comments to add to that above.

**Comment by tomhjp** [comment]
Added in #84, we'll be releasing it later this week.
