### ISSUE TITLE
Generic support for other secrets engines

### ISSUE THREAD

**Issue by gw0** [hashicorp/vault-csi-provider#76]
Currently, this Vault CSI provider only supports static secrets from the KV secrets engine. And assumes that secrets are versioned and that `/data/` should be automatically added to paths. Because Vault has many other secrets engines (which provide dynamic credentials that are much better in terms of security), the Vault CSI provider should provide a generic interface to support them.

Basically, one would want something like a `vault-agent` that could update a Secret (without using hacks such as annotations and webhooks that inject sidecar containers).

**Comment by tomhjp** [comment]
Hi, thanks for your interest in the project. We actually have these features in the master branch and will shortly be releasing them:

> this Vault CSI provider only supports static secrets from the KV secrets engine.

The next release will support all secret engines, including things like PKI which require using PUTs

> And assumes that secrets are versioned and that /data/ should be automatically added to paths

Both of these are stripped out in master
