### ISSUE TITLE
learn tutorial does not work

### ISSUE THREAD

**Issue by mmckane** [hashicorp/vault-csi-provider#94]
It appears that the learn tutorial is no longer functional through katacode.

**Comment by kalafut** [comment]
cc @burtio

**Comment by yhyakuna** [comment]
@mmckane We'll look into it.  Thank you for reporting.

**Comment by mmckane** [comment]
Was able to complete the lab and it appears to be working thanks @burtlo. Helps to have this working so I can play with it prior to adding it to one of our sandbox clusters!

**Comment by burtlo** [comment]
@mmckane, I'm glad that it's all working now. I really appreciate you finding and reporting the issue.
