### ISSUE TITLE
Support for HTTPS_PROXY with Proxy certificates

### ISSUE THREAD

**Issue by git001** [hashicorp/vault-csi-provider#98]
Lets assume you are in a restricted network which runs Kubernetes in a public Cloud and you have to talk with the on-prem Vault via a HTTPS interception Proxy.

I haven't seen a call of "ProxyFromEnvironment" so I assume it's not yet part of the provider.

Is there any plan to add this feature to the provider?

**Comment by tomhjp** [comment]
Happy to re-open this at a later date, but I'll close for now.
